#!/usr/bin/env bash

set -e

if [[ ! -d "${DALIAS_ROOT}/shims" ]]; then
	mkdir -p "${DALIAS_ROOT}/shims"
fi

if [[ ! -d "${DALIAS_ROOT}/links" ]]; then
	mkdir -p "${DALIAS_ROOT}/links"
fi

cat <<EOS
export PATH="${DALIAS_ROOT}/shims:\${PATH}"
EOS
