#!/bin/bash

set -e

abort() {
	echo "$1" >&2
	exit 1
}

ensure_shim() {
	[[ -d "${DALIAS_ROOT}/shims" ]] || mkdir -p "${DALIAS_ROOT}/shims"

	if [[ ! -x "${DALIAS_ROOT}/shims/dalias-exec-shim" ]]; then
		cat << EOF > "${DALIAS_ROOT}/shims/dalias-exec-shim"
#!/bin/bash

set -e

cmd=\$(basename \$0)

exec dalias exec \$cmd "\$@"
EOF
		chmod +x "${DALIAS_ROOT}/shims/dalias-exec-shim"
	fi

	if [[ ! -h "${DALIAS_ROOT}/shims/$dalias_command" ]]; then
		ln -sf "${DALIAS_ROOT}/shims/dalias-exec-shim" "${DALIAS_ROOT}/shims/$dalias_command"
		hash -r
	fi
}

create_local_alias() {
	[[ -d $DALIAS_LOCAL ]] || mkdir -p $DALIAS_LOCAL

	if [[ -x "$DALIAS_LOCAL/$dalias_command" ]]; then
		abort "$alias_command is already aliased"
	else
		cat << EOF > $DALIAS_LOCAL/$dalias_command
#!/bin/bash
exec $@ "\$@"
EOF
		chmod +x "$DALIAS_LOCAL/$dalias_command"
	fi
	return 0
}

dalias_command=$1
shift

ensure_shim $@
create_local_alias $@
