#!/usr/bin/env bash

set -e

DALIAS_LINKS_FILE="${DALIAS_ROOT}/links.csv"

alias_count() {
	if [[ ! -f "${DALIAS_LINKS_FILE}" ]]; then
		echo "0"
		return
	fi
	alias_name="$1"
	alias_path=""
	[[ $# -gt 1 ]] && alias_path="$2"
	search_line="^${alias_name},"
	if [[ -n "${alias_path}" ]]; then
		search_line="${search_line}${alias_path}"
	fi

	echo "$(grep -c "${search_line}" "${DALIAS_LINKS_FILE}" || true)"
}

delete_shim_symlink() {
	alias_name="$1"
	if [[ -h "${DALIAS_ROOT}/shims/${alias_name}" ]]; then
		rm "${DALIAS_ROOT}/shims/${alias_name}"
	fi
}

remove_from_store() {
	alias_name="$1"
	alias_path="$2"
	if [[ -f "${DALIAS_LINKS_FILE}" ]]; then
		records="$(grep -v "${alias_name},${alias_path}" "${DALIAS_LINKS_FILE}" || true)"
		echo "${records}" > "${DALIAS_ROOT}/links.new"
		mv "${DALIAS_ROOT}/links.new" "${DALIAS_LINKS_FILE}"
	fi
}

delete_local_alias() {
	alias_name="$1"
	alias_path="$2"
	if [[ -x "${alias_path}" ]]; then
		rm "${alias_path}"
	fi
	remove_from_store "${alias_name}" "${alias_path}"
}

nuke_alias() {
	alias_name="$1"
	aliases=$(grep "^${alias_name}," "${DALIAS_LINKS_FILE}" || ( "" ))
	OLD_IFS="${IFS}"
	for alias in ${aliases[@]}; do
		IFS=","
		chunks=( ${alias} )
		delete_local_alias "${chunks[0]}" "${chunks[1]}"
	done
	IFS="${OLD_IFS}"
}

global=0
alias_name=""

OPTIND=1
while getopts "g" opt; do
	case "${opt}" in
		g)
			global=1
			;;
		*)
			echo "Unrecognized argument: ${opt}" >&2
			exit 1
			;;
	esac
done

shift "$((OPTIND-1))"

alias_name="$1"

delete_local_alias "${alias_name}" "${DALIAS_LOCAL}/${alias_name}"
if [[ "$global" -eq 1 ]]; then
	nuke_alias "${alias_name}"
fi

if [[ "$(alias_count "${alias_name}")" -eq 0 ]]; then
	delete_shim_symlink "${alias_name}"
fi

echo "When removing a dalias, it is important to update your shell's"
echo "hash table.  Execute the following in all open shells:"
echo ""
echo "$ hash -d ${alias_name}"
echo ""
echo "Alternatively, simply restart your shell."
