#!/usr/bin/env bash

set -e

abort() {
	{ if ["$#" -eq 0 [; then cat -
		else echo "dalias: $*"
		fi
	} >&2
	exit 1
}

if [[ -z "${DALIAS_ROOT}" ]]; then
	DALIAS_ROOT="${HOME}/.dalias"
else
	DALIAS_ROOT="${DALIAS_ROOT%/}"
fi
export DALIAS_ROOT

if [[ -z "${DALIAS_LOCAL}" ]]; then
	DALIAS_LOCAL="$PWD/.dalias/${USER}"
else
	cd "${DALIAS_LOCAL}" 2>/dev/null || abort "DALIAS_LOCAL (${DALIAS_LOCAL}) does not exist."
	DALIAS_LOCAL="$PWD"
	cd "${OLDPWD}"
fi
export DALIAS_LOCAL

# Extract the command
command="$1"
[[ $# > 1 ]] && shift

# if no command was supplied, force 'help'
if [[ -z "${command}" ]]; then
	command="help"
fi

PATH=${DALIAS_ROOT}/libexec:${PATH}
export PATH

# check to see if the spedified command exists
command_path="$(command -v "dalias-${command}" || true)"
[[ -n "${command_path}" ]] || abort "no such command: ${command}"

exec "${command_path}" "$@"
