#!/bin/bash

set -e

alias_name="$1"
shift

echo "${DALIAS_LOCAL}/${alias_name}"
if [[ -x "${DALIAS_LOCAL}/${alias_name}" ]]; then
	exec "${DALIAS_LOCAL}/${alias_name}" $@
fi

# If we're here, there was no local alias defined.
# Remove the shim directory from the path and exec
orig_path="${PATH}"
PATH=$(echo ${PATH} | sed -e "s|:${DALIAS_ROOT}/shims[^:]*||" | sed -e "s|^${DALIAS_ROOT}/shims:||")
cmd=$(command -v ${alias_name} || true)
if [[ -n "${cmd}" ]]; then
	PATH="${orig_path}"
	exec "${cmd}" "$@"
fi

# Nothing left to do.  Bail.
echo "dalias: ${alias_name}: command not found" >&2
exit 127
